# Owner of the GitHub repository
owner: SRESchool

# Name of the GitHub repository
repo: All-Motoshare-Websites-Uptime-Monitor

user-agent: pritesh-1904
skipReadme: true
skipDescription: true
skipTopics: true

# List of websites to monitor for uptime and SSL
sites:
  - name: MotoShare Asia
    url: https://motoshare.asia
    ssl: true
  - name: MotoShare Canada
    url: https://motoshare.ca
    ssl: true
  - name: MotoShare Colombia
    url: https://motoshare.co
    ssl: true
  - name: MotoShare China
    url: https://motoshare.com.cn
    ssl: true
  - name: MotoShare Indonesia
    url: https://motoshare.id
    ssl: true
  - name: MotoShare India
    url: https://motoshare.in
    ssl: true
  - name: MotoShare Mexico
    url: https://motoshare.mx
    ssl: true
  - name: MotoShare Japan
    url: https://motoshare.jp
    ssl: true
  - name: MotoShare USA
    url: https://motoshare.us
    ssl: true
  - name: MotoShare Africa
    url: https://motoshareafrica.com
    ssl: true    
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  cname: null
  baseUrl: /All-Motoshare-Websites-Uptime-Monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime/master/assets/logo.png
  name: MotoShare Websites Uptime Monitor
  introTitle: MotoShare Websites Status
  introMessage: This page shows the uptime and SSL status of MotoShare websites.
  favicon: https://raw.githubusercontent.com/upptime/upptime/master/assets/favicon.ico
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Workflow schedule (every 5 minutes)
workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/15 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
  ssl: "*/5 * * * *"

# Committer configuration
committer:
  name: Pritesh
  email: contact@motoshare.in

# Email notification configuration
notifications:
  - type: email
    smtpTo: contact@motoshare.in
    smtpFrom: contact@motoshare.in
    smtpHost: smtp.gmail.com
    smtpPort: 587
    smtpUsername: contact@motoshare.in
    smtpPassword: kmxg nshc vsrf kxqj

# Assignees for issues
assignees:
  - pritesh-1904
